#!/bin/bash
set -euo pipefail

psql -U postgres -c "drop database raw1"

psql -U postgres -c "create database raw1"

psql -U postgres -d raw1 -f rawdata_small.backup 

psql -U postgres -d raw1 -f B2_build_movie_db.sql
